
if (hit.hit) {
    vec3 new_dir = normalize(hit.normal + get_random_direction());//get_random_hemisphere_direction(hit.normal);
    if (new_dir == vec3(0.0, 0.0, 0.0)) {
        new_dir = normalize(hit.normal + get_random_direction() + 1);//get_random_hemisphere_direction(hit.normal);
    }
    ray = Ray(hit.point + hit.normal, new_dir);
    hit = voxel_hit(ray);
    light += hit.material.emissive_color * hit.material.emissive_strength * color.rgb;
    color *= hit.material.color;
}
