
if (hit.hit) {
    vec3 new_dir = get_random_hemisphere_direction(hit.normal, get_pixel_id());
    if (new_dir == vec3(0.0, 0.0, 0.0)) {
        new_dir = get_random_hemisphere_direction(hit.normal, get_pixel_id()+NN*(i+100)*89433);
    }
    ray = Ray(hit.point + hit.normal, new_dir);
    hit = voxel_hit(ray);
    light += hit.material.emissive_color * hit.material.emissive_strength * color.rgb;
    color *= hit.material.color;
}
